### ISSUE TITLE
Need reactive supports for properties

### ISSUE THREAD

**Issue by newbie95** [allenhwkim/elements-x#8]
Attributes given to the element are not reactive

**Comment by allenhwkim** [comment]
Not all elements are reactive to attribute changes.
Please let me know which elements needs to have reactive attributes.

**Comment by newbie95** [comment]
why elements need not to be reactive any reason?. It would nice if we have reactive attributes for the elements

**Comment by newbie95** [comment]
Any update on this

**Comment by allenhwkim** [comment]
I agree with you. It's better to be reactive.

To have a reactive attribute with custom elements, each attribute change must be coded and maintained.
It's some effort and more maintenance required. 

For example
If the type attribute changes, the whole contents needs to be reinitialized
`<x-input type="text"></x-input>`
`<x-input type="date"></x-input>`

At this point, I thought it was un necessary to keep the code as simple as possible.
However, if users wants I am ready to make changes.

Every attribute needs to be reactive is too much work and I think it's unnecessary(this opinion may change :))
